CREATE TABLE rooms (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(255));
CREATE TABLE sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, room INTEGER, timeCreated INTEGER);
CREATE TABLE whiteboards (id INTEGER PRIMARY KEY AUTOINCREMENT, session INTEGER, idInRoom INTEGER, x INTEGER, y INTEGER, page INTEGER, size INTEGER, data TEXT);